version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
    - 'cbrand/vodafone-billing-downloader:{{ .Tag }}-amd64'
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
  - image_templates:
    - 'cbrand/vodafone-billing-downloader:{{ .Tag }}-arm64'
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64"
    goarch: arm64
  - image_templates:
    - 'ghcr.io/cbrand/vodafone-billing-downloader:{{ .Tag }}-amd64'
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
  - image_templates:
    - 'ghcr.io/cbrand/vodafone-billing-downloader:{{ .Tag }}-arm64'
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64"
    goarch: arm64
docker_manifests:
- name_template: 'cbrand/vodafone-billing-downloader:{{ .Version }}'
  image_templates: &image_templates
  - 'cbrand/vodafone-billing-downloader:{{ .Tag }}-amd64'
  - 'cbrand/vodafone-billing-downloader:{{ .Tag }}-arm64'
- name_template: 'cbrand/vodafone-billing-downloader:latest'
  image_templates: &image_templates
  - 'cbrand/vodafone-billing-downloader:{{ .Tag }}-amd64'
  - 'cbrand/vodafone-billing-downloader:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/cbrand/vodafone-billing-downloader:latest'
  image_templates: &image_templates
  - 'ghcr.io/cbrand/vodafone-billing-downloader:{{ .Tag }}-amd64'
  - 'ghcr.io/cbrand/vodafone-billing-downloader:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/cbrand/vodafone-billing-downloader:{{.Version}}'
  image_templates: &image_templates
  - 'ghcr.io/cbrand/vodafone-billing-downloader:{{ .Tag }}-amd64'
  - 'ghcr.io/cbrand/vodafone-billing-downloader:{{ .Tag }}-arm64'

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
